#include "stm32f0xx_hal.h"

volatile uint8_t button_pressed = 0;

// A ISR for the button 1 that activates the button on a press.
void EXTI4_15_IRQHandler(void) {
  //__disable_irq();
  // clear the
  // extended interrupt and event controller
  // controls what to do with signal generated by async event (a button press)
  EXTI->PR |= (1 << 13);

  // button_pressed = !button_pressed;
  button_pressed = 1;
  //__enable_irq();
}
